pipeline {
  agent{
    // dockerfile {
    //     filename 'Dockerfile'
    //     label 'docker'
    // }
    docker {
        image 'golang:1.18-alpine'
        label 'docker'
    }
  }

  environment {
    GOOS='windows'
    GOARCH='amd64'
    XDG_CACHE_HOME='/tmp/.cache'
    // jenkins managed credential
    CREDENTIALS_ID='blitz-esports'
    GCS_BUCKET='jenkins-poc/go-web-dev'
    IAM_CREDENTIALS_ID='jeknins-poc'
    S3_RELEASE_BUCKET='blitz-releases/jenkins-poc'
  } 

  stages {
    stage("Setup Environment") {
      steps {
        echo "Golang OS: ${GOOS}"
        echo "Golang Arch: ${GOARCH}"
        // remove previous build dir, if exists
        sh "rm -rf go-web-dev"
      }
    }

    stage("Build") {
      steps {
        // build
        sh "go build -o build/ go-web-dev"
        sh "mkdir -p build/images/galleries"
        // copy static assets
        sh "cp -r ./config build/"
        sh "cp -r ./views build/"
        sh "rm build/views/*.go"
        // compress artifact
        sh "mv build go-web-dev"
        sh "tar -czf \"go-web-dev_${GOOS}_${GOARCH}.tar.gz\" go-web-dev"
      }
    }

    // Test step could go here.

    stage("Deploy") {
      steps {
        // store in jenkkins
        archiveArtifacts artifacts: '**/go-web-dev*.tar.gz', allowEmptyArchive: false
        // store in GCS w/ plugin
        step([$class: 'ClassicUploadStep', credentialsId: env.CREDENTIALS_ID,  bucket: "gs://${env.GCS_BUCKET}",
                 pattern: '**/go-web-dev*.tar.gz'])
        // store in S3 w/ plugin
        withAWS(region:'us-west-2',credentials:"${IAM_CREDENTIALS_ID}") {
                    def identity=awsIdentity();
                // Upload files from working directory to project workspace
                s3Upload(bucket:"${S3_RELEASE_BUCKET}", includePathPattern:'**/go-web-dev*.tar.gz');
            }
      }
    }
  }

}